### ISSUE TITLE
segmentation fault / sigsegv error

### ISSUE THREAD

**Issue by m4gr4th34** [olealgoritme/gddr6#1]
Hi, thanks for working on this!  I compile using
`gcc gddr6.c -o gddr6 -lpci`

no errors, but when i run ./gddr6, i get Segmentation fault.  I followed instructions for apt install, and updated grub and rebooted (twice).

**Comment by m4gr4th34** [comment]
Not sure what happened, but now I get a different error.  I'm using RTX 3090, and I didn't change anything else in the system (and using sudo and su gives same error):
`terminated by signal SIGSEGV (Address boundary error)`

**Comment by olealgoritme** [comment]
Are you running a single NVIDIA RTX 3000/4000 series GPU or multiple?
Please provide the output of the following, it prints the PCIe bar0 address(es).

``` 
lspci -v -d 10de: | grep 'size=16M' | awk '{print $3}'
```

**Comment by olealgoritme** [comment]
I pushed a change to add that specific bar0. Pull and retry.

**Comment by m4gr4th34** [comment]
Thanks!  Tried it, double triple checked folder, recompiled, checked code, and the entry seems to be correct for bar0, but I still get:
`Segmentation fault`

**Comment by olealgoritme** [comment]
It can be a bit tricky. I removed the bar0 depend in recent fix, but probably won't change anything.
Try ``` sudo gdb ./gddr6``` and run it inside the debugger (print 'run', press enter)

**Comment by m4gr4th34** [comment]
I ran the second iteration of the code and received this error:
`Program received signal SIGSEGV, Segmentation fault.
0x0000555555555483 in pci_detect_dev ()`

I will try the latest iteration now

**Comment by m4gr4th34** [comment]
Alright, it works in debug:
`[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Device: RTX 3090 (GA102 / 0x2204)
GDDR6X VRAM Temp: 56°c`

and it works in:
`sudo ./gddr6`

this is very sweet, thanks!

**Comment by olealgoritme** [comment]
Awesome! Glad it worked for you.
